---

name: Download and generate blocklists

on:
  schedule: # https://crontab.guru
    - cron: '0 */2 * * *' # At minute 0 past every 2nd hour.

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          lfs: true

      - name: Set up Git LFS
        run: git lfs install

      - name: Download blocklists
        run: bash bash/download.sh

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prepare templates
        run: node scripts/prepare-templates.js

      - name: Track large files
        run: |
          find . -type f -name '*.txt' -size +100M | xargs -I {} git lfs track "{}"
          git add .gitattributes

      - name: Add files to staging
        run: git add .

      - name: Commit and push changes
        run: |
          git config --global user.name "Sefinek Actions"
          git config --global user.email "sefinek.actions@gmail.com"
          if [ -n "$(git status -s)" ]; then
            git status
            git commit -m "Download blocklists and update files"
            git push origin main
          else
            echo "Canceled. No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SEFINEK_ACTIONS_PAT }}
