---

name: Generate new committed blocklists

on:
  push:
    branches:
      - main
    paths:
      - '**.txt'

  workflow_dispatch:

jobs:
  generate:
    runs-on: sefin-vps

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prepare templates
        run: node scripts/prepare-templates.js

      - name: Remove duplicates
        run: node scripts/remove-duplicates.js

      - name: Remove domains that are on the whitelist
        run: node scripts/whitelist.js

      - name: Lint
        run: node scripts/lint.js

      # - name: Create everything list
      #  run: node scripts/create-everything-list.js

      - name: Generate No IP list
        run: node scripts/generate/noip.js

      - name: Generate 0.0.0.0 list
        run: node scripts/generate/0.0.0.0.js

      - name: Generate 127.0.0.1 list
        run: node scripts/generate/127.0.0.1.js

      - name: Generate AdGuard list
        run: node scripts/generate/adguard.js

      - name: Generate Dnsmasq list
        run: node scripts/generate/dnsmasq.js

      - name: Count domains
        run: node scripts/update-number-of-domains.js --ignore-question

      - name: Commit and push changes
        run: |
          git config --global user.name "Sefinek Actions"
          git config --global user.email "sefinek.actions@gmail.com"
          git add .
          if [ -n "$(git status -s)" ]; then
            git status
            git commit -m "Update committed blocklist files"
            git push
          else
            echo "Canceled. No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SEFINEK_ACTIONS_PAT }}
