---

name: Proof HTML

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: anishathalye/proof-html@v2
        with:
          directory: ./
